### ISSUE TITLE
重命名集数不正确

### ISSUE THREAD

**Issue by cutiechi** [wushuo894/ani-rss#100]
### 请勾选您确认过的前置条件

- [X] 我已经阅读了 [常见问题](https://docs.wushuo.top/faq.html) [使用文档](https://docs.wushuo.top/add-rss.html)

- [X] 我确定没有重复的issue或discussions

- [X] 我确定这是程序本身的问题而不是其他 (比如网络相关的报错)

- [X] 我确定这个问题在最新版本中没有被修复

### 运行环境

- [X] Docker

- [ ] Linux

- [ ] macOS

- [ ] Windows

- [ ] 群晖套件

### 程序版本

v1.1.202

### 问题描述

第二季的剧集种子命名可能不是第二集第 3 集这样，而是绝对的，比如说 27 集，实际是第二季第 2 集：

<img width="1178" alt="image" src="https://github.com/user-attachments/assets/8192ee46-7338-4959-af8f-0d6ee53ffad4">

在重命名的时候会重命名成 S02E27，正常应该是 S02E02

**Comment by cutiechi** [comment]
还是说需要手动配置？

<img width="797" alt="image" src="https://github.com/user-attachments/assets/2170b406-b1a1-495e-b594-a478c6f865b6">

**Comment by abo2029** [comment]
应该可以设置，多研究下文档，我记得有处理方式

**Comment by wushuo894** [comment]
设置集数偏移就好了

**Comment by cutiechi** [comment]
> 设置集数偏移就好了

确实可以，感谢大佬
