### ISSUE TITLE
自定义只下载最新的N集（ latest x ep ）

### ISSUE THREAD

**Issue by pein0saga** [wushuo894/ani-rss#107]
### 请勾选您确认过的前置条件

- [X] 我已经确认此功能还未实现

### 需求描述

有时候看过前面两三集，中间咸鱼了一段时间。只需要下载最近的n集就可以了。

### 实现思路

每个番剧补漏的情况都不同，毕竟每个人兴趣不同，时间有限，可以加强自定义能力，也不需要复杂的正则表达式基础。

**Comment by wushuo894** [comment]
> ### 请勾选您确认过的前置条件
> * [x]  我已经确认此功能还未实现
> 
> ### 需求描述
> 有时候看过前面两三集，中间咸鱼了一段时间。只需要下载最近的n集就可以了。
> 
> ### 实现思路
> 每个番剧补漏的情况都不同，毕竟每个人兴趣不同，时间有限，可以加强自定义能力，也不需要复杂的正则表达式基础。
> 
> ### 附件
> _No response_

在预览里面你就可以设置禁止下载某集

**Comment by wushuo894** [comment]
> > 置禁止下载某集
> 
> 我想确认下，禁止下载某集是不需要勾选“自定义下载”的吧？“自定义下载”生效的仅仅只是下载位置吧？

是的
