### ISSUE TITLE
“死神 千年血战篇-相克谭” 订阅时日语标题自动获取严重错误

### ISSUE THREAD

**Issue by pein0saga** [wushuo894/ani-rss#111]
### 请勾选您确认过的前置条件

- [X] 我已经阅读了 [常见问题](https://docs.wushuo.top/faq.html) [使用文档](https://docs.wushuo.top/add-rss.html)

- [X] 我确定没有重复的issue或discussions

- [X] 我确定这是程序本身的问题而不是其他 (比如网络相关的报错)

- [X] 我确定这个问题在最新版本中没有被修复

### 运行环境

- [ ] Docker

- [ ] Linux

- [ ] macOS

- [ ] Windows

- [X] 群晖套件

### 程序版本

v1.1.207

### 问题描述

如果设置日文的TMDB则是错误的标题“死神坊ちゃんと黒メイド” （本人备注：死神少爷和黑女仆）

(https://www.themoviedb.org/tv/117992?language=ja-JP) (2021) 

正确的标题应当是：TMDB的主标题BLEACH (2004)下的季标题 [BLEACH 千年血戦篇]

(https://www.themoviedb.org/tv/30984-bleach/season/2?language=ja-JP) (2022)

如果时简体繁体版本的TMDB则是死神 (2004) ，也会和以前的老动画的正剧标题产生冲突；

如果设置英文则是9集的电视剧[Shinigami-kun](https://www.themoviedb.org/tv/65068?language=zh-SG) (2014) 而不是Thousand-Year Blood War (2022)

我的建议是暂时回滚掉TMDB原生的多语种标题功能，改成可选切换BGM.TV的日语标题，因为蜜柑计划本身就是和BGM网站一一对应的，可以保证日语标题的绝对正确性。

以死神为例子，TMDB 是 死神 (2004)为主标题，然后下面各个季标题，而且季还是不细分的。

蜜柑计划把季标题 BLEACH 千年血戦篇拆成了2022的[死神 千年血战篇](https://bgm.tv/subject/302286)，2023的 [BLEACH 千年血戦篇-訣別譚-](https://bgm.tv/subject/412916) ，和2024的[BLEACH 千年血戦篇-相剋譚-](https://bgm.tv/subject/457326)，分类不但合理准确，更精细化，而且和每年追番的节奏更吻合。（PS：我个人用的视频管理服务是开源的https://github.com/ikaros-dev/ikaros ，用的是BANGUMI刮削的信息，也契合蜜柑计划）

如果刻意迎合TMDB的多语种体系不但不切实际实用性低而且吃力不讨好（小众的多语种刮削可以自定义下载那重命名），

我认为现在用BGM.TV的日语标题更加合适方便准确，一点即亮。

### 日志

![image](https://github.com/user-attachments/assets/e6658f14-dcce-4f48-bdb8-37ed34d5e2cf)

**Comment by wushuo894** [comment]
增加了获取bgm日文标题的开关，可以和获取tmdb标题配合使用
