### ISSUE TITLE
mac部署后程序自动生成的文件无读写权限

### ISSUE THREAD

**Issue by zhaodakeng** [wushuo894/ani-rss#113]
### 请勾选您确认过的前置条件

- [X] 我已经阅读了 [常见问题](https://docs.wushuo.top/faq.html) [使用文档](https://docs.wushuo.top/add-rss.html)

- [X] 我确定没有重复的issue或discussions

- [X] 我确定这是程序本身的问题而不是其他 (比如网络相关的报错)

- [X] 我确定这个问题在最新版本中没有被修复

### 运行环境

- [ ] Docker

- [ ] Linux

- [X] macOS

- [ ] Windows

- [ ] 群晖套件

### 程序版本

1.1.208

### 问题描述

mac 使用程序部署后，生成的目录以及文件程序无法正常写入，需要手动更改目录权限后才能正常保存配置或者写入种子文件

**Comment by wushuo894** [comment]
你是如何部署的，使用以下命令吗？

```bash
wget https://github.com/wushuo894/ani-rss/raw/master/docker/run.sh

sudo chmod -R 777 ./run.sh

sudo bash ./run.sh
```

**Comment by zhaodakeng** [comment]
对的
&nbsp;


该邮件从移动设备发送


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年12月11日(星期三) 中午11:42
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [wushuo894/ani-rss] mac部署后程序自动生成的文件无读写权限 (Issue #113)















你是如何部署的，使用以下命令吗？
韦捷https://github.com/wushuo894/ani-rss/raw/master/docker/run.shsudochmod -R 777./run.shsudo bash./ run.sh

-
直接回复这封邮件，在GitHub上查看，或取消订阅.
***@***.*** &gt;

**Comment by wushuo894** [comment]
因为是 sudo bash ./run.sh 执行的，所以用户属于root

你也可以直接执行 bash ./run.sh 不要加 sudo。这样应该就没问题了
