### ISSUE TITLE
"本地存在"的检测部分好像有bug

### ISSUE THREAD

**Issue by kanoto** [wushuo894/ani-rss#117]
### 请勾选您确认过的前置条件

- [X] 我已经阅读了 [常见问题](https://docs.wushuo.top/faq.html) [使用文档](https://docs.wushuo.top/add-rss.html)

- [X] 我确定没有重复的issue或discussions

- [X] 我确定这是程序本身的问题而不是其他 (比如网络相关的报错)

- [X] 我确定这个问题在最新版本中没有被修复

### 运行环境

- [ ] Docker

- [X] Linux

- [ ] macOS

- [ ] Windows

- [ ] 群晖套件

### 程序版本

v1.1.209

### 问题描述

Linux下非Docker部署, 使用的非Docker的qbittorrent.

添加一个新的番剧任务时, 在所有下载任务都被添加到qbittorrent里之前, qbittorrent出现过一次崩溃, 恢复之后发现该番剧仅有一部分被下载, 而本地检测认为所有任务本地都已经存在.

"预览"中显示所有剧集本地都已经存在
![image](https://github.com/user-attachments/assets/852345fe-e932-4bdd-bb87-c6d4d7494f83)

而实际目录中只有1-5集

    root@v-1:/data/ANI-RSS/番剧/地。 ―关于地球的运动―# tree
    .
    └── Season 1
        ├── 地。 ―关于地球的运动― S01E01.mkv
        ├── 地。 ―关于地球的运动― S01E02.mkv
        ├── 地。 ―关于地球的运动― S01E03.mkv
        ├── 地。 ―关于地球的运动― S01E04.mkv
        └── 地。 ―关于地球的运动― S01E05.mkv
    
    2 directories, 5 files

目前似乎只能删掉整个番剧重新添加

### 日志

      287 2024-12-12 16:35:23.932 [pool-2-thread-249] INFO  ani.rss.util.TorrentUtil - 下载种子 地。 ―关于地球的运动― S01E06
      288 2024-12-12 16:35:25.109 [pool-2-thread-249] ERROR ani.rss.util.HttpRequestPlus - url: http://127.0.0.1:10554/api/v2/torrents/add, error: ConnectException: Connection refused
      289 2024-12-12 16:35:25.111 [pool-2-thread-249] ERROR ani.rss.util.TorrentUtil - ConnectException: Connection refused
      290 cn.hutool.core.io.IORuntimeException: ConnectException: Connection refused
      291     at cn.hutool.http.HttpRequest.send(HttpRequest.java:1350)
      292     at cn.hutool.http.HttpRequest.doExecute(HttpRequest.java:1188)
      293     at cn.hutool.http.HttpRequest.execute(HttpRequest.java:1051)
      294     at ani.rss.util.HttpRequestPlus.execute(HttpRequestPlus.java:42)
      295     at cn.hutool.http.HttpRequest.thenFunction(HttpRequest.java:1077)
      296     at ani.rss.download.qBittorrent.download(qBittorrent.java:169)
      297     at ani.rss.util.TorrentUtil.download(TorrentUtil.java:629)
      298     at ani.rss.util.TorrentUtil.downloadAni(TorrentUtil.java:201)
      299     at ani.rss.action.AniAction.lambda$post$5(AniAction.java:123)
      300     at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
      301     at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
      302     at java.base/java.lang.Thread.run(Thread.java:1583)
      303 Caused by: java.net.ConnectException: Connection refused
      304     at java.base/sun.nio.ch.Net.pollConnect(Native Method)
      305     at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:682)
      306     at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:542)
      307     at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:592)
      308     at java.base/java.net.Socket.connect(Socket.java:751)
      309     at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:178)
      310     at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:531)
      311     at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:636)
      312     at java.base/sun.net.www.http.HttpClient.<init>(HttpClient.java:280)
      313     at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:386)
      314     at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:408)
      315     at java.base/sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1319)
      316     at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1252)
      317     at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1138)
      318     at java.base/sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:1067)
      319     at java.base/sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1461)
      320     at java.base/sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1432)
      321     at cn.hutool.http.HttpConnection.getOutputStream(HttpConnection.java:461)
      322     at cn.hutool.http.HttpRequest.sendMultipart(HttpRequest.java:1402)
      323     at cn.hutool.http.HttpRequest.send(HttpRequest.java:1340)
      324     ... 11 common frames omitted
      325 2024-12-12 16:35:25.112 [pool-2-thread-249] ERROR ani.rss.util.TorrentUtil - 地。 ―关于地球的运动― S01E06 添加失败，疑似为坏种

**Comment by wushuo894** [comment]
有种子缓存，自己删除

**Comment by wushuo894** [comment]
https://docs.wushuo.top/faq.html#删除了视频-在预览中还是显示本地存在

**Comment by kanoto** [comment]
> [https://docs.wushuo.top/faq.html#删除了视频-在预览中还是显示本地存在](https://docs.wushuo.top/faq.html#%E5%88%A0%E9%99%A4%E4%BA%86%E8%A7%86%E9%A2%91-%E5%9C%A8%E9%A2%84%E8%A7%88%E4%B8%AD%E8%BF%98%E6%98%AF%E6%98%BE%E7%A4%BA%E6%9C%AC%E5%9C%B0%E5%AD%98%E5%9C%A8)

谢谢
