### ISSUE TITLE
nginx反代，登录失效

### ISSUE THREAD

**Issue by ain-soph** [wushuo894/ani-rss#118]
### 运行环境

- [X] Docker

### 程序版本

v1.1.209

### 问题描述

我部署在本地端口后可以正常登录访问；通过nginx反代到`ani-rss.mydomain.com`之后，能正常看到登录界面，但是输入用户名密码之后会显示“登录失效”，并且返回登陆界面。应该是来自于这段java，auth失效了。

偶尔能登录进入使用界面中，但是一刷新或者一点什么按钮就又登录失效回到登陆界面了

https://github.com/wushuo894/ani-rss/blob/7eecc1cb7f748c44bec8f62379583e7efcf57567/src/main/java/ani/rss/auth/fun/Header.java#L33

### 日志

<img width="1920" alt="image" src="https://github.com/user-attachments/assets/a88172bc-63b8-4497-b3a9-91346e616372" />

### 额外信息
我使用的是linuxserver的swag https://hub.docker.com/r/linuxserver/swag （docker的nginx），里面默认的proxy.conf已经设置了以下转发（包括websocket）

```
# Proxy Header Settings
proxy_set_header Connection $connection_upgrade;
proxy_set_header Early-Data $ssl_early_data;
proxy_set_header Host $host;
proxy_set_header Proxy "";
proxy_set_header Upgrade $http_upgrade;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Host $host;
proxy_set_header X-Forwarded-Method $request_method;
proxy_set_header X-Forwarded-Port $server_port;
proxy_set_header X-Forwarded-Proto $scheme;
proxy_set_header X-Forwarded-Server $host;
proxy_set_header X-Forwarded-Ssl on;
proxy_set_header X-Forwarded-Uri $request_uri;
proxy_set_header X-Original-Method $request_method;
proxy_set_header X-Original-URL $scheme://$http_host$request_uri;
proxy_set_header X-Real-IP $remote_addr;
```

**Comment by wushuo894** [comment]
在登陆设置中关闭ip校验

**Comment by ain-soph** [comment]
> 在登陆设置中关闭ip校验

感谢🙏，关闭后已经可以正常登录了

**Comment by ain-soph** [comment]
如果能在readme或者软件里面note一下这个，应该会对其他人有所帮助。反代应该还是挺常用的
