### ISSUE TITLE
优化遗漏检测的前端显示

### ISSUE THREAD

**Issue by mhqschen** [wushuo894/ani-rss#119]
### 请勾选您确认过的前置条件

- [x] 我已经确认此功能还未实现

### 需求描述

现在首页只能看到RSS包含集数/总集数。
1. 看不出RSS里缺了哪集。
2. 也看不出RSS包含的剧集哪些没有下载（要点修改订阅——预览，才能看到，而且未下载完成的在预览里也显示“本地存在”）

建议新增一个页面，显示总集数的清单，然后类似预览里标注的那样，标注RSS是否遗漏，是否已下载

**Comment by wushuo894** [comment]
> ### 请勾选您确认过的前置条件
> * [x]  我已经确认此功能还未实现
> 
> ### 需求描述
> 现在首页只能看到RSS包含集数/总集数。
> 
> 1. 看不出RSS里缺了哪集。
> 2. 也看不出RSS包含的剧集哪些没有下载（要点修改订阅——预览，才能看到，而且未下载完成的在预览里也显示“本地存在”）
> 
> 建议新增一个页面，显示总集数的清单，然后类似预览里标注的那样，标注RSS是否遗漏，是否已下载
> 
> ### 实现思路
> _No response_
> 
> ### 附件
> _No response_

https://docs.wushuo.top/faq.html#删除了视频-在预览中还是显示本地存在
