### ISSUE TITLE
订阅及重命名问题

### ISSUE THREAD

**Issue by starlightor** [wushuo894/ani-rss#121]
### 请勾选您确认过的前置条件

- [X] 我已经阅读了 [常见问题](https://docs.wushuo.top/faq.html) [使用文档](https://docs.wushuo.top/add-rss.html)

- [X] 我确定没有重复的issue或discussions

- [X] 我确定这是程序本身的问题而不是其他 (比如网络相关的报错)

- [X] 我确定这个问题在最新版本中没有被修复

### 运行环境

- [ ] Docker

- [ ] Linux

- [ ] macOS

- [ ] Windows

- [X] 群晖套件

### 程序版本

v1.1.214

### 问题描述

1、添加已有较多集的番剧时只能下载第1集，手动刷新一次下载一集
2、自动重命名失败

### 日志

[ani-rss.log](https://github.com/user-attachments/files/18209124/ani-rss.log)

**Comment by wushuo894** [comment]
已经发现问题原因，是因为群晖套件的权限导致的。docker没有此问题。需要等套件更新修复

**Comment by wushuo894** [comment]
已修复，更新套件试试。如果没问题我会关闭issues
