### ISSUE TITLE
本季度新番关于地球的运动LoliHouse字幕组订阅后无法获取到任何信息

### ISSUE THREAD

**Issue by GaLiPaiGLP** [wushuo894/ani-rss#122]
### 请勾选您确认过的前置条件

- [X] 我已经阅读了 [常见问题](https://docs.wushuo.top/faq.html) [使用文档](https://docs.wushuo.top/add-rss.html)

- [X] 我确定没有重复的issue或discussions

- [X] 我确定这是程序本身的问题而不是其他 (比如网络相关的报错)

- [X] 我确定这个问题在最新版本中没有被修复

### 运行环境

- [ ] Docker

- [ ] Linux

- [ ] macOS

- [X] Windows

- [ ] 群晖套件

### 程序版本

v1.1.214

### 问题描述

订阅关于地球的运动LoliHouse字幕组会出现预览中什么都没有的情况。把排除啥的都删了也不行。换成北宇治字幕组的rss就一切正常了。

### 日志

2024-12-22 03:03:47 DEBUG ani.rss.util.HttpReq - 代理未开启 https://mikanime.tv/RSS/Bangumi?bangumiId=3488&subgroupid=370
2024-12-22 03:03:48 DEBUG ani.rss.util.TorrentUtil - 地。 ―关于地球的运动― 共 0 个
![image](https://github.com/user-attachments/assets/91461dec-3349-473b-9356-58780d9b1e1b)
![image](https://github.com/user-attachments/assets/214213e6-a3b9-4ad2-9775-dca0d894d47d)
![QQ_1734808421034](https://github.com/user-attachments/assets/64ecafad-d9fb-4b08-a85d-a8fa37ede22b)
![QQ_1734808434029](https://github.com/user-attachments/assets/21a05218-5e21-4e5b-a6b3-1f4de9accbd3)

**Comment by wushuo894** [comment]
开一下 **自定义集数规则**

**Comment by GaLiPaiGLP** [comment]
开启后已解决
