### ISSUE TITLE
订阅备用RSS搜索的时候遇到的两个问题

### ISSUE THREAD

**Issue by pein0saga** [wushuo894/ani-rss#123]
### 请勾选您确认过的前置条件

- [X] 我已经阅读了 [常见问题](https://docs.wushuo.top/faq.html) [使用文档](https://docs.wushuo.top/add-rss.html)

- [X] 我确定没有重复的issue或discussions

- [X] 我确定这是程序本身的问题而不是其他 (比如网络相关的报错)

- [X] 我确定这个问题在最新版本中没有被修复

### 运行环境

- [ ] Docker

- [ ] Linux

- [ ] macOS

- [ ] Windows

- [X] 群晖套件

### 程序版本

v1.1.214

### 问题描述

1. 很多番靠日文标题搜不出来（“ありふれた職業で世界最強”，即使只打前几个假名也不行），“搜索结果为空”；有些番用日语可以搜索出来。我在设置中选中了BGM日文标题，它默认用日文搜索。
2. 中文标题搜索的搜索结果需要优化，比如“平凡职业造就世界最强“第三季，用”平凡“搜索，第三个就是；用”世界最“搜索第三季直接搜不到了，反而出现的是第一1、2季和其他番。在系统限制搜索结果数目的时候（猜测），至少应该提高当季番作为结果之一的权重，而且只出现四个限制得有点多了。
3. 帮我确认下上述问题，不确定是否是网络不稳定导致的，写issue的时候反正代理测试全通的，日志里面网络不稳定的错误也是几小时前的
![20241222123934002](https://github.com/user-attachments/assets/d6af2c8d-3e6e-451e-91e5-1dde0feaed68)

**Comment by wushuo894** [comment]
蜜柑限制了搜索结果为4个
