### ISSUE TITLE
x86黑裙更新最新版本1.1.214后启动不了

### ISSUE THREAD

**Issue by unclecat86** [wushuo894/ani-rss#125]
### 请勾选您确认过的前置条件

- [X] 我已经阅读了 [常见问题](https://docs.wushuo.top/faq.html) [使用文档](https://docs.wushuo.top/add-rss.html)

- [X] 我确定没有重复的issue或discussions

- [X] 我确定这是程序本身的问题而不是其他 (比如网络相关的报错)

- [X] 我确定这个问题在最新版本中没有被修复

### 运行环境

- [ ] Docker

- [ ] Linux

- [ ] macOS

- [ ] Windows

- [x] 群晖套件

### 程序版本

1.1.214

### 问题描述

![image](https://github.com/user-attachments/assets/ec9d26e7-377c-4a66-85e1-54889eaedc2e)

### 日志

![image](https://github.com/user-attachments/assets/8733dbf8-574a-4687-b661-c6af88e06b9e)

**Comment by wushuo894** [comment]
卸载套件，不要清理套件数据。再安装试试

**Comment by wushuo894** [comment]
套件日志位置 /volume1/@appdata/ani-rss/ani-rss.log

**Comment by unclecat86** [comment]
> 卸载套件，不要清理套件数据。再安装试试

重启NAS解决，重启后日志
[ani-rss.log](https://github.com/user-attachments/files/18222002/ani-rss.log)

**Comment by unclecat86** [comment]
> 套件日志位置 /volume1/@appdata/ani-rss/ani-rss.log

重启后之前的日志好似没了

**Comment by wushuo894** [comment]
解决了就好

**Comment by unclecat86** [comment]
> 解决了就好

感谢大佬提供这么好的工具!
