### ISSUE TITLE
UI 建议

### ISSUE THREAD

**Issue by Yuri-NagaSaki** [wushuo894/ani-rss#13]
移除底部分页，将底部空间腾出来，现在高分辨率显示器显得底部很空，还需要调整页面显示数量。

![image](https://github.com/user-attachments/assets/45734261-faeb-4281-a8f9-a8c5b5b6e35d)
可以参考 [anichart](https://anichart.net/Fall-2024) 做成瀑布流，直接无线下拉
![QQ_1726021547969](https://github.com/user-attachments/assets/2bce98c4-5f18-4927-b652-f657c764cf46)

将退出登录 移动到顶部菜单栏

![QQ_1726021625040](https://github.com/user-attachments/assets/d543d457-a773-4295-80b2-efa30bea0e3b)

**Comment by Yuri-NagaSaki** [comment]
还有黑暗模式

**Comment by SakuyaInory** [comment]
希望在订阅里可以自定义星期几更新（类似订阅信息那设置季度，只不过这里设置星期几），首页就可以根据星期分类

**Comment by wushuo894** [comment]
> 还有黑暗模式

更新了
