### ISSUE TITLE
希望在修改订阅处增加一个给每部番剧的单独的保存位置

### ISSUE THREAD

**Issue by ygh1159146961** [wushuo894/ani-rss#18]
你好作者大大，我是习惯每个季度建立一个文件夹，然而ani-rss只是在全局设置那里的一个保存位置没法分开每个季度的更新番剧，希望可以在每部订阅的修改订阅处加一个保存位置的设置。
![image](https://github.com/user-attachments/assets/85afe59b-3991-402d-bcbb-043b609c99ec)
比如我在qb的rss订阅设置里是这样的
![image](https://github.com/user-attachments/assets/c7cfc9a3-8d99-42f6-87f1-6d9169d1037e)

**Comment by wushuo894** [comment]
在计划中

**Comment by ygh1159146961** [comment]
> 在计划中

好的！期待！

**Comment by wushuo894** [comment]
已实现
