### ISSUE TITLE
反馈和建议

### ISSUE THREAD

**Issue by sola614** [wushuo894/ani-rss#19]
问题：
* 全局排除设置规则后，再通过底下的mikan按钮搜索添加，排除那一行只有默认的720，设置的都没带出来，重建docker也不行

建议：
* 支持mikan的搜索rss订阅，有些冷门资源，mikan没有汇总，只能通过搜索来订阅，如：https://mikanani.me/RSS/Search?searchstr=%E5%81%87%E9%9D%A2%E9%AA%91%E5%A3%AB%E5%8A%A0%E5%B8%83 ，希望能支持

**Comment by wushuo894** [comment]
全局排除和订阅的排除是两个东西
并没有带出一说，开启了开关就自动使用了
实际的排除是 全局+订阅自己设置的

你说的冷门资源没有汇总，因为软件的信息获取都是用的mikan，所以不好支持
而且ani-rss 和 mikan 的目的是追番，并不包含特摄剧

**Comment by sola614** [comment]
明白了，最后还是建议排除那个能不能做成带出呢，可以增删，最后以订阅为准，这样更灵活？

**Comment by wushuo894** [comment]
> 明白了，最后还是建议排除那个能不能做成带出呢，可以增删，最后以订阅为准，这样更灵活？

ok
