### ISSUE TITLE
[功能建议] 建议添加一个开关控制是否需要重命名磁力名

### ISSUE THREAD

**Issue by jinghuashang** [wushuo894/ani-rss#20]
之前使用auto，因为那个项目摆烂了故转战ani，不过用了一段时间后稍觉得在重命名方面。将磁力名也一块改了，感觉稍微有点不妥。
如我下同一部的多个版本，重命名后我并不知道哪个是之前的版本哪个是最新版本，望作者能添加这个功能。

**Comment by wushuo894** [comment]
已实现
