### ISSUE TITLE
[BUG反馈]  docker v1.1.19 升级 v1.1.20 无线重启

### ISSUE THREAD

**Issue by Yuri-NagaSaki** [wushuo894/ani-rss#21]
系统：debian12

![QQ_1726208354841](https://github.com/user-attachments/assets/adacded0-e081-4b69-8713-a1f83b401d94)
![image](https://github.com/user-attachments/assets/50ac673b-397f-40b7-a317-3c136610feed)

**Comment by wushuo894** [comment]
可以看一下你的配置文件config/config.json 里 webHookBody 是怎样的吗
