### ISSUE TITLE
请问有没有考虑给已经订阅的番剧，按季度整理在一起，而不是所有订阅都在一个页面里

### ISSUE THREAD

**Issue by ygh1159146961** [wushuo894/ani-rss#23]
如题，就像这样（下面是我的jellyfin的截图）
![image](https://github.com/user-attachments/assets/ebe06e8e-9c98-4357-bc1b-fa0de395ab66)

**Comment by ygh1159146961** [comment]
在qb的RSS里我是分别建立了个文件夹弄得
![image](https://github.com/user-attachments/assets/3e767452-5186-4fad-957f-415d34fb3212)

**Comment by wushuo894** [comment]
> 在qb的RSS里我是分别建立了个文件夹弄得 ![image](https://private-user-images.githubusercontent.com/131505798/367201181-3e767452-5186-4fad-957f-415d34fb3212.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYyMTUxMTgsIm5iZiI6MTcyNjIxNDgxOCwicGF0aCI6Ii8xMzE1MDU3OTgvMzY3MjAxMTgxLTNlNzY3NDUyLTUxODYtNGZhZC05NTdmLTQxNWQzNGZiMzIxMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxM1QwODA2NThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zYjhiZDA4MzcxZTJlODI5N2IxZjJlNGVlZTM5MTEyMWQ1MDU3ZDJhOTY0NmMwZWQ4YmNhZTgxMDMxOGMwNjg3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.S3cYYlbhPyWvm59GEKkgXIRihEWkM73Fpzo9tho2w3Q)

计划中

**Comment by ygh1159146961** [comment]
> > 在qb的RSS里我是分别建立了个文件夹弄得 ![image](https://private-user-images.githubusercontent.com/131505798/367201181-3e767452-5186-4fad-957f-415d34fb3212.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYyMTUxMTgsIm5iZiI6MTcyNjIxNDgxOCwicGF0aCI6Ii8xMzE1MDU3OTgvMzY3MjAxMTgxLTNlNzY3NDUyLTUxODYtNGZhZC05NTdmLTQxNWQzNGZiMzIxMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxM1QwODA2NThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zYjhiZDA4MzcxZTJlODI5N2IxZjJlNGVlZTM5MTEyMWQ1MDU3ZDJhOTY0NmMwZWQ4YmNhZTgxMDMxOGMwNjg3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.S3cYYlbhPyWvm59GEKkgXIRihEWkM73Fpzo9tho2w3Q)
> 
> 计划中

好的！

**Comment by wushuo894** [comment]
已实现
