### ISSUE TITLE
新增设置，允许路径不添加第几季

### ISSUE THREAD

**Issue by sqb2020** [wushuo894/ani-rss#26]
作者你好，在增加新订阅时，番剧的默认下载路径为“downloadPath”+”番剧名“+季度，比如：D:/Syncthing/物语系列 外传季&怪物季/Season 1。![image](https://github.com/user-attachments/assets/c4b9afdf-4d47-41fa-b334-c5ad584a370e)
虽然可以手动自定义下载路径，但是希望可以新增一个设置，允许下载路径不添加第几季，直接“downloadPath”+”番剧名“即可，也就是保存到D:/Syncthing/物语系列 外传季&怪物季。

**Comment by wushuo894** [comment]
有自定义下载啊，你可以手动删除

**Comment by wushuo894** [comment]
这样刮削时不会出现问题吗

**Comment by sqb2020** [comment]
> 这样刮削时不会出现问题吗

按照Jellyfin的官方介绍，视频的文件夹及文件命名有一定要求。第一种格式是按季分类，先创建主剧集文件夹，再新建子季度文件夹。番外放在「Season 00」文件夹中，第一季放在「Season 01」文件夹中，以此类推。第二种格式则是直接剧集的所有节目都放在同一级文件夹中，比如：
动画
├── 狼与香辛料 (2008) [第一种方法]
│   ├── Season 00
│   │   ├── 狼与香辛料 S00E02.mkv
│   │   └── 狼与香辛料 S00E02.mkv
│   ├── Season 01
│   │   ├── 狼与香辛料 S01E01.mkv
│   │   ├── 狼与香辛料 S01E02.mkv
│   │   ├── 狼与香辛料 S01E03.mkv
│   │   └── 狼与香辛料 S01E04.mkv
│   └── Season 02
│       ├── 狼与香辛料 S02E01.mkv
│       └── 狼与香辛料 S02E02.mkv
└── 3月的狮子 (2016) [第二种方法]
    ├── 3月的狮子 S01E01.mkv
    ├── 3月的狮子 S01E02.mkv
    ├── 3月的狮子 S02E01.mkv
    ├── 3月的狮子 S02E02.mkv
    └── 3月的狮子 S02E03.mkv
所以如果某部动画只有一季，希望可以不必创建「Season 01」文件夹，直接全丢到主文件夹中。

参考教程：https://www.himiku.com/archives/deploy-a-more-comfortable-animation-library-with-jellyfin-and-bangumi.html#fn-7

**Comment by wushuo894** [comment]
已实现
