### ISSUE TITLE
希望可以加一个一键更新所有订阅的按钮

### ISSUE THREAD

**Issue by ygh1159146961** [wushuo894/ani-rss#27]
比如在这个位置加一个一键更新
![image](https://github.com/user-attachments/assets/3e1bb643-0006-48ed-a637-a229173b9f37)
例如qb的rss这种
![image](https://github.com/user-attachments/assets/ae747a2b-6b62-46d2-bbf5-773c52e8cace)

**Comment by wushuo894** [comment]
已实现
