### ISSUE TITLE
日志提示：添加失败，疑似为坏种。。。实际已经在qb里添加成功

### ISSUE THREAD

**Issue by LianXia233** [wushuo894/ani-rss#29]
日志提示：添加失败，疑似为坏种。。实际已经在qb里添加成功

![QQ20240917-110908.png](https://s2.loli.net/2024/09/17/CM7UnPuj8AwvtQi.png)

![QQ20240917-110924.png](https://s2.loli.net/2024/09/17/g5wIo7DiM3N9BLR.png)

**Comment by wushuo894** [comment]
> 日志提示：添加失败，疑似为坏种。。实际已经在qb里添加成功
> 
> ![QQ20240917-110908.png](https://camo.githubusercontent.com/fe289819ae983f1e9fd724ce3c4daa1041612b6bd1818fb226b64855b703ee94/68747470733a2f2f73322e6c6f6c692e6e65742f323032342f30392f31372f434d37556e50756a384177767451692e706e67)
> 
> ![QQ20240917-110924.png](https://camo.githubusercontent.com/a2eeceab95965e689d0d66412859177cc8ff6cf8900bb7acf914c200513dd9c6/68747470733a2f2f73322e6c6f6c692e6e65742f323032342f30392f31372f673577496f3744694d334e39424c522e706e67)

看到你图中的rss并不在支持范围，这个rss的种子应该不是hash

**Comment by LianXia233** [comment]
选择的就是动漫花园，图上链接是动漫花园反代

**Comment by wushuo894** [comment]
由于动漫花园在rss提供的是磁力而非种子文件，因此不好判断其hash

**Comment by wushuo894** [comment]
我会更改在动漫花园判断坏种的方法
