### ISSUE TITLE
关闭了跳过.5功能，但是无法正常下载

### ISSUE THREAD

**Issue by ygh1159146961** [wushuo894/ani-rss#31]
如图，字幕组是有6.5集的，设置里也关闭跳过.5了，但是没有下载6.5集
![image](https://github.com/user-attachments/assets/c01e646c-398a-4336-845d-a19914109c87)

![image](https://github.com/user-attachments/assets/34883faf-f334-4cd2-9206-bec212a4f0fa)

![image](https://github.com/user-attachments/assets/49411a2c-e6a7-4b0d-a5e3-d415babf01e9)

![image](https://github.com/user-attachments/assets/482dda9e-2b19-4233-b75b-c0a9064ab208)

**Comment by wushuo894** [comment]
.5跳过是用来避免遗漏的.5排除，本身是不支持.5的重命名的。因为.5和S00E0X没有明确的关系

**Comment by ygh1159146961** [comment]
> .5跳过是用来避免遗漏的.5排除，本身是不支持.5的重命名的。因为.5和S00E0X没有明确的关系

那可不可以检测到.5就不做任何操作按原名下载，这样的话至少我知道有一集.5，即使nastool会因为识别不了名称而刮削错误，也会发消息提醒我刮削失败，我可以去手动刮削，而不是我都不知道还有一集.5，毕竟开了自动订阅和自动下载后，基本就很少再去看每天更新了哪些集数了。
比如这季度的物语系列，6.5并非总集篇而是有新剧情的特别篇，如果跳过了这集还是会缺失一集的剧情体验的。

**Comment by wushuo894** [comment]
> > .5跳过是用来避免遗漏的.5排除，本身是不支持.5的重命名的。因为.5和S00E0X没有明确的关系
> 
> 那可不可以检测到.5就不做任何操作按原名下载，这样的话至少我知道有一集.5，即使nastool会因为识别不了名称而刮削错误，也会发消息提醒我刮削失败，我可以去手动刮削，而不是我都不知道还有一集.5，毕竟开了自动订阅和自动下载后，基本就很少再去看每天更新了哪些集数了。 比如这季度的物语系列，6.5并非总集篇而是有新剧情的特别篇，如果跳过了这集还是会缺失一集的剧情体验的。

.5的出现还是少数，目前还是自己处理吧
因为.5非int整数如果要支持的话程序改动较大

**Comment by ygh1159146961** [comment]
> > > .5跳过是用来避免遗漏的.5排除，本身是不支持.5的重命名的。因为.5和S00E0X没有明确的关系
> > 
> > 
> > 那可不可以检测到.5就不做任何操作按原名下载，这样的话至少我知道有一集.5，即使nastool会因为识别不了名称而刮削错误，也会发消息提醒我刮削失败，我可以去手动刮削，而不是我都不知道还有一集.5，毕竟开了自动订阅和自动下载后，基本就很少再去看每天更新了哪些集数了。 比如这季度的物语系列，6.5并非总集篇而是有新剧情的特别篇，如果跳过了这集还是会缺失一集的剧情体验的。
> 
> .5的出现还是少数，目前还是自己处理吧 因为.5非int整数如果要支持的话程序改动较大

主要是开启自动订阅后，只会知道有哪些下载了，而不会知道没有哪些下载了，会出现我并不知道有.5出现而没被下载的情况，现在因为是在试用ani，所有每个订阅我都有去查看是不是正常下载。
开了自动订阅和自动下载后，以后就基本不会再去看订阅的情况了，这也是自动化的初衷，所以希望还是能支持一下.5。
即使要手动处理，我也得知道有个没法被自动刮削的.5存在才行 XD

**Comment by wushuo894** [comment]
> > > > .5跳过是用来避免遗漏的.5排除，本身是不支持.5的重命名的。因为.5和S00E0X没有明确的关系
> > > 
> > > 
> > > 那可不可以检测到.5就不做任何操作按原名下载，这样的话至少我知道有一集.5，即使nastool会因为识别不了名称而刮削错误，也会发消息提醒我刮削失败，我可以去手动刮削，而不是我都不知道还有一集.5，毕竟开了自动订阅和自动下载后，基本就很少再去看每天更新了哪些集数了。 比如这季度的物语系列，6.5并非总集篇而是有新剧情的特别篇，如果跳过了这集还是会缺失一集的剧情体验的。
> > 
> > 
> > .5的出现还是少数，目前还是自己处理吧 因为.5非int整数如果要支持的话程序改动较大
> 
> 主要是开启自动订阅后，只会知道有哪些下载了，而不会知道没有哪些下载了，会出现我并不知道有.5出现而没被下载的情况，现在因为是在试用ani，所有每个订阅我都有去查看是不是正常下载。 开了自动订阅和自动下载后，以后就基本不会再去看订阅的情况了，这也是自动化的初衷，所以希望还是能支持一下.5。 即使要手动处理，我也得知道有个没法被自动刮削的.5存在才行 XD

可以增加一个出现.5的通知

**Comment by ygh1159146961** [comment]
> > > > > .5跳过是用来避免遗漏的.5排除，本身是不支持.5的重命名的。因为.5和S00E0X没有明确的关系
> > > > 
> > > > 
> > > > 那可不可以检测到.5就不做任何操作按原名下载，这样的话至少我知道有一集.5，即使nastool会因为识别不了名称而刮削错误，也会发消息提醒我刮削失败，我可以去手动刮削，而不是我都不知道还有一集.5，毕竟开了自动订阅和自动下载后，基本就很少再去看每天更新了哪些集数了。 比如这季度的物语系列，6.5并非总集篇而是有新剧情的特别篇，如果跳过了这集还是会缺失一集的剧情体验的。
> > > 
> > > 
> > > .5的出现还是少数，目前还是自己处理吧 因为.5非int整数如果要支持的话程序改动较大
> > 
> > 
> > 主要是开启自动订阅后，只会知道有哪些下载了，而不会知道没有哪些下载了，会出现我并不知道有.5出现而没被下载的情况，现在因为是在试用ani，所有每个订阅我都有去查看是不是正常下载。 开了自动订阅和自动下载后，以后就基本不会再去看订阅的情况了，这也是自动化的初衷，所以希望还是能支持一下.5。 即使要手动处理，我也得知道有个没法被自动刮削的.5存在才行 XD
> 
> 可以增加一个出现.5的通知

这样也可以

**Comment by wushuo894** [comment]
> > > > > > .5跳过是用来避免遗漏的.5排除，本身是不支持.5的重命名的。因为.5和S00E0X没有明确的关系
> > > > > 
> > > > > 
> > > > > 那可不可以检测到.5就不做任何操作按原名下载，这样的话至少我知道有一集.5，即使nastool会因为识别不了名称而刮削错误，也会发消息提醒我刮削失败，我可以去手动刮削，而不是我都不知道还有一集.5，毕竟开了自动订阅和自动下载后，基本就很少再去看每天更新了哪些集数了。 比如这季度的物语系列，6.5并非总集篇而是有新剧情的特别篇，如果跳过了这集还是会缺失一集的剧情体验的。
> > > > 
> > > > 
> > > > .5的出现还是少数，目前还是自己处理吧 因为.5非int整数如果要支持的话程序改动较大
> > > 
> > > 
> > > 主要是开启自动订阅后，只会知道有哪些下载了，而不会知道没有哪些下载了，会出现我并不知道有.5出现而没被下载的情况，现在因为是在试用ani，所有每个订阅我都有去查看是不是正常下载。 开了自动订阅和自动下载后，以后就基本不会再去看订阅的情况了，这也是自动化的初衷，所以希望还是能支持一下.5。 即使要手动处理，我也得知道有个没法被自动刮削的.5存在才行 XD
> > 
> > 
> > 可以增加一个出现.5的通知
> 
> 这样也可以

已经支持.5你可以使用wushuo894/ani-rss:test测试，如果有问题进群反馈
