### ISSUE TITLE
检测 本地是否存在 失效

### ISSUE THREAD

**Issue by Naivc** [wushuo894/ani-rss#34]
我已经删了本地文件夹，刷新后还是显示 本地存在：是

![Captura de pantalla 2024-10-03 093056](https://github.com/user-attachments/assets/939919f4-bced-4569-b31e-0c61a21477c3)
![Captura de pantalla 2024-10-03 093046](https://github.com/user-attachments/assets/a7de44d2-e98b-485a-aec2-b9053eff0ebe)

**Comment by wushuo894** [comment]
https://docs.wushuo.top/faq#%E5%88%A0%E9%99%A4%E4%BA%86%E8%A7%86%E9%A2%91-%E5%9C%A8%E9%A2%84%E8%A7%88%E4%B8%AD%E8%BF%98%E6%98%AF%E6%98%BE%E7%A4%BA%E6%9C%AC%E5%9C%B0%E5%AD%98%E5%9C%A8
