### ISSUE TITLE
重命名自定义建议

### ISSUE THREAD

**Issue by 1277848257** [wushuo894/ani-rss#35]
希望添加自定义重命名的格式，比如我之前的动漫命名都是 “番剧名 - SxxExx - 字幕组名” 便于后面可能的BD洗版或者其他需求

**Comment by 1277848257** [comment]
![Snipaste_2024-10-04_16-16-50](https://github.com/user-attachments/assets/045d089d-1205-4a7b-8f1e-9db2328d18b5)

设置特定格式的重命名后似乎只在qbit列表中生效，对实际的文件没有生效？

**Comment by wushuo894** [comment]
> ![Snipaste_2024-10-04_16-16-50](https://private-user-images.githubusercontent.com/86863845/373562248-045d089d-1205-4a7b-8f1e-9db2328d18b5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgwMzA5OTksIm5iZiI6MTcyODAzMDY5OSwicGF0aCI6Ii84Njg2Mzg0NS8zNzM1NjIyNDgtMDQ1ZDA4OWQtMTIwNS00YTdiLThmMWUtOWRiMjMyOGQxOGI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA0VDA4MzEzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQxNGJhYTY4MTBlYmJiNTJmOGQ1MmM3ZjMyZjY4NTNhYWVhNDk1NjNjMjBiZmJlMmU0ZTNkYjA1NDQ3ZjgxM2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.mBOkCLbgMLw98IJtRBYJN36RS5-mqa8pmkHbHo2O1n0)
> 
> 设置特定格式的重命名后似乎只在qbit列表中生效，对实际的文件没有生效？

你结尾不是SxxExx导致的，等会发个版本改掉

**Comment by wushuo894** [comment]
1.1.90 解决了

**Comment by peaynan** [comment]
不出意外又出意外了（），自定义重命名格式后的洗版可能有一点问题，不会自动删除之前的文件

比如我订阅了lolihouse和animerep的青之箱，由于我的自定义重命名是 "${title} - S${seasonFormat}E${episodeFormat} - ${subgroup}" 所以主rss和备用rss下载的文件同一集命名是不一样的（字幕组不一样），猜测可能洗版的原理是根据命名直接覆盖。

不知道这个修起来困不困难或者说有没有必要，不急着修可以在设置里面写个注释
很抱歉多次打扰

**Comment by wushuo894** [comment]
> 不出意外又出意外了（），自定义重命名格式后的洗版可能有一点问题，不会自动删除之前的文件
> 
> 
> 
> 比如我订阅了lolihouse和animerep的青之箱，由于我的自定义重命名是 "${title} - S${seasonFormat}E${episodeFormat} - ${subgroup}" 所以主rss和备用rss下载的文件同一集命名是不一样的（字幕组不一样），猜测可能洗版的原理是根据命名直接覆盖。
> 
> 
> 
> 不知道这个修起来困不困难或者说有没有必要，不急着修可以在设置里面写个注释
> 
> 很抱歉多次打扰

你如果路径映射的没有问题，会自动根据SxxExx删除旧的视频。你检查一下映射吧

**Comment by wushuo894** [comment]
> 不出意外又出意外了（），自定义重命名格式后的洗版可能有一点问题，不会自动删除之前的文件
> 
> 
> 
> 比如我订阅了lolihouse和animerep的青之箱，由于我的自定义重命名是 "${title} - S${seasonFormat}E${episodeFormat} - ${subgroup}" 所以主rss和备用rss下载的文件同一集命名是不一样的（字幕组不一样），猜测可能洗版的原理是根据命名直接覆盖。
> 
> 
> 
> 不知道这个修起来困不困难或者说有没有必要，不急着修可以在设置里面写个注释
> 
> 很抱歉多次打扰

如果编辑上面的那个按钮点开有视频列表，就是映射没有问题的![image](https://github.com/user-attachments/assets/33f359dd-cedc-418a-a97e-3a15ad7c3333)

**Comment by wushuo894** [comment]
貌似是现有的代码有问题，今天修复
