### ISSUE TITLE
今天更新以后不能正常重命名了。。。

### ISSUE THREAD

**Issue by wsh258** [wushuo894/ani-rss#36]
只能看到日志里有ERROR ani.rss.task.RenameTask - ，不知道什么原因导致的

**Comment by wushuo894** [comment]
> 只能看到日志里有ERROR ani.rss.task.RenameTask - ，不知道什么原因导致的

版本号是什么，有个问题在102修复了

**Comment by wsh258** [comment]
> 版本号是什么，有个问题在102修复了
就是1.1.102，docker直接更新的
