### ISSUE TITLE
mikan 个别番搜索不到

### ISSUE THREAD

**Issue by ljjwy168** [wushuo894/ani-rss#38]
比如夏目友人帐7 换关键字也搜索不到

**Comment by wushuo894** [comment]
> 比如夏目友人帐7 换关键字也搜索不到

夏目友人帐 七


中文

**Comment by ljjwy168** [comment]
> > 比如夏目友人帐7 换关键字也搜索不到
> 
> 夏目友人帐 七
> 
> 中文
谢谢 可以了

**Comment by ljjwy168** [comment]
> > 比如夏目友人帐7 换关键字也搜索不到
> 
> 夏目友人帐 七
> 
> 中文

还有个问题 下载老的完结番，比如食草龙第一季 anirss上就显示7~12集 看不到前面的6集 下载也不下前面6集 怎么设置可以下载前面的6集

**Comment by wushuo894** [comment]
> > > 比如夏目友人帐7 换关键字也搜索不到
> > 
> > 
> > 夏目友人帐 七
> > 中文
> 
> 还有个问题 下载老的完结番，比如食草龙第一季 anirss上就显示7~12集 看不到前面的6集 下载也不下前面6集 怎么设置可以下载前面的6集

你看看那前六集是不是合集，不支持合集下载
或者被排除规则排除掉了
