### ISSUE TITLE
用 javaw 命令启动时，之前的用户数据会丢失

### ISSUE THREAD

**Issue by OBraveNewWorld** [wushuo894/ani-rss#40]
window11
之前一直用java 命令启动的。
java -jar -Xmx1g D:\tools\Ani-RSS\ani-rss-jar-with-dependencies.jar --port 7789 --gui

后来觉得老是设置自动开机后还弹出个窗太麻烦了就换成javaw了。然后发现javaw只能启动一个全新的ani-rss，之前的所有用户数据不见了。

**Comment by OBraveNewWorld** [comment]
找到了，之前的config文件夹在C:\Users\Administrator文件夹下面

**Comment by wushuo894** [comment]
> 找到了，之前的config文件夹在C:\Users\Administrator文件夹下面

你是不是开机启动发现丢失的，开机启动时程序运行目录不是程序所在目录，windows是这样的
