### ISSUE TITLE
蜜柑反复搜索时，前面展开的番剧依旧展开，但无内容

### ISSUE THREAD

**Issue by wahaha216** [wushuo894/ani-rss#41]
版本号 v1.1.109

起初想订阅 `地。-关于地球的运动- ` ，发现搜索 `地球` 搜不到，但 `地球的运动` 或者 `运动` 能搜到，在尝试更换搜索词时发现的这个小问题

复现步骤：
1. 先搜索某个番剧，如 `运动` ，并展开 `地。-关于地球的运动- `
![PixPin_2024-10-09_19-27-15](https://github.com/user-attachments/assets/30bc0f64-7106-47dc-9451-61e0a6a85989)
2. 再次点击搜索， `地。-关于地球的运动- ` 还是展开状态，但里面的数据已经没了，需要收起重新展开
![PixPin_2024-10-09_19-27-54](https://github.com/user-attachments/assets/09565ba7-6c68-4015-8936-425af4a4ff57)

**Comment by wushuo894** [comment]
v1.1.110 已修复
