### ISSUE TITLE
一些操作逻辑UI建议

### ISSUE THREAD

**Issue by Jaie0801** [wushuo894/ani-rss#42]
![WechatIMG520](https://github.com/user-attachments/assets/76203cd1-3ea1-487a-84b4-09a508f807af)
<img width="867" alt="image" src="https://github.com/user-attachments/assets/a7f6c376-1d80-493b-980d-099b137bbd85">

**Comment by Jaie0801** [comment]
<img width="1047" alt="image" src="https://github.com/user-attachments/assets/dc4df94e-259f-44e1-9169-8574f741d60e">

**Comment by wushuo894** [comment]
评分是通过bgm获取的，bgm的接口都是有流控的，不可能每个番剧都一一查出来并显示的，会导致每次请求都特别慢
图片小暂时不能修改，碍于组件限制
其他都已经实现

**Comment by Jaie0801** [comment]
> 评分是通过bgm获取的，bgm的接口都是有流控的，不可能每个番剧都一一查出来并显示的，会导致每次请求都特别慢 图片小暂时不能修改，碍于组件限制 其他都已经实现

看到更新了，作者更新很快，点赞，订阅逻辑还能再优化一下。
<img width="1292" alt="image" src="https://github.com/user-attachments/assets/bd78100b-2cf2-4394-967f-3199c0810249">

关于bgm的接口流控问题，可以做一些策略降低这个问题
1.设置里增加查询开关(默认关)
2.箭头展开后再去bmg请求评分接口，以此来减少网站请求次数
3.默认只查询当日的番剧的评分

<img width="783" alt="image" src="https://github.com/user-attachments/assets/b9fcab7e-bce6-4268-9f42-67761d72d9db">

**Comment by wushuo894** [comment]
> > 评分是通过bgm获取的，bgm的接口都是有流控的，不可能每个番剧都一一查出来并显示的，会导致每次请求都特别慢 图片小暂时不能修改，碍于组件限制 其他都已经实现
> 
> 
> 
> 看到更新了，作者更新很快，点赞，订阅逻辑还能再优化一下。
> 
> <img width="1292" alt="image" src="https://github.com/user-attachments/assets/bd78100b-2cf2-4394-967f-3199c0810249">
> 
> 
> 
> 关于bgm的接口流控问题，可以做一些策略降低这个问题
> 
> 1.设置里增加查询开关(默认关)
> 
> 2.箭头展开后再去bmg请求评分接口，以此来减少网站请求次数
> 
> 3.默认只查询当日的番剧的评分
> 
> 
> 
> <img width="783" alt="image" src="https://github.com/user-attachments/assets/b9fcab7e-bce6-4268-9f42-67761d72d9db">
> 
> 
> 
> 

即使这样也不行，每次请求最少要间隔1秒的。

**Comment by Jaie0801** [comment]
> > > 评分是通过bgm获取的，bgm的接口都是有流控的，不可能每个番剧都一一查出来并显示的，会导致每次请求都特别慢 图片小暂时不能修改，碍于组件限制 其他都已经实现
> > 
> > 
> > 看到更新了，作者更新很快，点赞，订阅逻辑还能再优化一下。
> > <img alt="image" width="1292" src="https://private-user-images.githubusercontent.com/40334764/375457459-bd78100b-2cf2-4394-967f-3199c0810249.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkyNDAyMzgsIm5iZiI6MTcyOTIzOTkzOCwicGF0aCI6Ii80MDMzNDc2NC8zNzU0NTc0NTktYmQ3ODEwMGItMmNmMi00Mzk0LTk2N2YtMzE5OWMwODEwMjQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE4VDA4MjUzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY2NGQzYjZhOTMwNzlkM2M4ODg3MjljYzExY2E5ZGY4OWNjM2VkYTQ0NmNmZWU0ZDI0OWY2NzZlNWRkMzM2NTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.zT9qMpWg079niyRr7506PWPlugOruW2tlE8ibaBNQAU">
> > 关于bgm的接口流控问题，可以做一些策略降低这个问题
> > 1.设置里增加查询开关(默认关)
> > 2.箭头展开后再去bmg请求评分接口，以此来减少网站请求次数
> > 3.默认只查询当日的番剧的评分
> > <img alt="image" width="783" src="https://private-user-images.githubusercontent.com/40334764/375461838-b9fcab7e-bce6-4268-9f42-67761d72d9db.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkyNDAyMzgsIm5iZiI6MTcyOTIzOTkzOCwicGF0aCI6Ii80MDMzNDc2NC8zNzU0NjE4MzgtYjlmY2FiN2UtYmNlNi00MjY4LTlmNDItNjc3NjFkNzJkOWRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE4VDA4MjUzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTczYjQ2NTQ5MWU3ZmUxODUyNjdiOWI3YjlmZjAwNGJiYzExYzRlZmRiYjE5OTcxNWFiMTVkM2FlMWQyNjIzMGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.lKO9JANO03UIS6sNQY5jrsaQRrvjFAJuUGrN4-j3_VI">
> 
> 即使这样也不行，每次请求最少要间隔1秒的。

# 1.是否可以每次只查询一次，只看一个的分数，刚好间隔一秒
![image](https://github.com/user-attachments/assets/22abeeee-9b3b-42c1-9a38-b43727cd4bc5)
# 2.点击取消或者订阅完成后，回退到上一级选择订阅的界面
不是直接完成或取消就退出
![image](https://github.com/user-attachments/assets/66009445-e559-4070-9e5a-54b49bb430c6)
