### ISSUE TITLE
tmdb适配建议

### ISSUE THREAD

**Issue by edhnt455** [wushuo894/ani-rss#44]
首先对作者的肝送上贴心的问候🙂，其次提个小建议，针对一些多季动漫的tmdb搜索建议优化。比如地下城第五季，默认的订阅标题是《期待在地下城邂逅有错吗V 丰饶的女神篇 (2024)》，下载路径是期待在地下城邂逅有错吗V 丰饶的女神篇 (2024)/Season 1。这样在tmdb是无法搜索的，而很多媒体库管理软件像是emby,jellyfin等的刮削都是依赖tmdb词条的，这样入库的结果就是一片空白，没有媒体信息看着不是很美。我需要自定义下载：/在地下城寻求邂逅是否搞错了什么 (2015)/Season 5
标题改成《在地下城寻求邂逅是否搞错了什么 (2015)》，季数选第5季，就能正常刮削。
期待作者能优化这个问题，尽量在tmdb上搜索到词条来填充信息

**Comment by wushuo894** [comment]
没办法完全匹配到，已经尽量优化
