### ISSUE TITLE
开启`只下载最新集`后 已下载集数为1

### ISSUE THREAD

**Issue by LockRim** [wushuo894/ani-rss#46]
## 问题描述
关闭`自动跳过`为了防止出现[v2]的情况
为了节省硬盘空间做完种+看过的视频会删除，所以开启`只下载最新集`
一开始获取时集数正确
![屏幕截图_20241012_142051](https://github.com/user-attachments/assets/2e4ec0cb-69ac-4a77-a8d3-b191cc719dd5)
刷新后集数错误
![屏幕截图_20241012_142135](https://github.com/user-attachments/assets/e4fb7302-1bd2-44c5-bf7b-3c5a09dbcb7e)
## 期望功能
希望开启的情况下直接使用最新集数作为已下载的集数

**Comment by wushuo894** [comment]
已优化
