### ISSUE TITLE
获取bgm信息失败，是否可以考虑从其他渠道获取信息

### ISSUE THREAD

**Issue by akiakise** [wushuo894/ani-rss#47]
偶发会有调用 bgm 接口超时的情况（已使用代理）：

![image](https://github.com/user-attachments/assets/9f150b08-96da-4753-b4b9-6a9753f433e8)

![image](https://github.com/user-attachments/assets/1f6d0b52-3169-41dd-8dd6-216747e1b27d)

而直接通过浏览器访问会显示 502：

![image](https://github.com/user-attachments/assets/5c04faca-33be-4085-b7c0-efb501767dbb)

看起来 bgm 服务端有一些问题，这个 issue https://github.com/bangumi/server/issues/642 也显示了正在处理，但是原因不明，解决时间不确定。

短期是否可以通过 tmdb 获取这部分信息？或者说在调用 bgm 超时后不阻塞添加流程，这部分信息由用户自己补全。

**Comment by wushuo894** [comment]
恢复后会使用github action做个缓存，能缓解这个问题

**Comment by akiakise** [comment]
OK，这类元信息缓存一下确实也是足够的了，不过 bgm 超时不阻塞添加流程这个可以考虑一下 ~
