### ISSUE TITLE
[功能建议] 是否考虑加入对mikan聚合rss的支持

### ISSUE THREAD

**Issue by windowBR** [wushuo894/ani-rss#48]
已知目前写的原因是如果一次过多更新会出现遗漏
但即使如此还是挺希望能加入这个功能的
然后比较好奇遗漏问题是 mikan 那边的 rss 问题还是这个项目在测试阶段出现的无法修复的问题

**Comment by wushuo894** [comment]
mikan的聚合rss如果项目太多了的话 会抛弃之前的
在缓存批量更新的情况下，直接挤掉很多信息
