### ISSUE TITLE
修改命名规则后，下载的任务名可以实现重命名，但是下载的文件名没有自动修改

### ISSUE THREAD

**Issue by LovelyTitan** [wushuo894/ani-rss#53]
重命名模板默认为：
${title} S${seasonFormat}E${episodeFormat}
我修改成了
${title} - s${seasonFormat}e${episodeFormat}

修改后，qBittorrent的任务名可以实现重命名，且新名字符合我修改后的模板，但是下载目录里的文件名没有自动修改，还是种子原始的名字。
如果我使用模板的默认设置，任务名和下载目录的文件名都可以自动修改，没什么问题。

EX：下载目录的季名，可否支持Season 01这样的格式呢

**Comment by wushuo894** [comment]
已解决

**Comment by TONGTIANTI** [comment]
> 已解决

请问怎么解决的，我也遇到这个问题了，QB的webUI里修改了名称，NAS里的文件夹不能同步修改，还是原种子文件名

**Comment by TONGTIANTI** [comment]
qBittorrent v5.0.3 WebUI 重命名文件修改方法：选中已下载的任务，在底部的详细信息里——内容——选中最外层文件夹——右键——重命名。实测可用,，虽然不如TR直接，但是凑活用吧，毕竟用的不多
![Snipaste_2025-01-09_11-39-11](https://github.com/user-attachments/assets/07af70c3-b5b3-4ab4-a160-151b066b7782)
