### ISSUE TITLE
[功能建议]希望自动点格子能支持Jellyfin

### ISSUE THREAD

**Issue by qinu321** [wushuo894/ani-rss#54]
试过Jellyfin的webhook，但ASS这边总是报错
不知有没有大佬提供下模板要怎么写？

**Comment by wushuo894** [comment]
{"Title":"item.markplayed","Date":"2024-10-16T08:44:55.8392893Z","Event":"item.markplayed","User":{"Name":"wushuo","Id":"a49bc32b976a4876bba8dfdfb651a2dc"},"Item":{"Name":"母与子","ServerId":"8203ffe900c941298803d360b3685052","Id":"904439","DateCreated":"2023-07-17T03:09:22.0000000Z","Container":"mkv","SortName":"母与子","PremiereDate":"2023-04-12T00:00:00.0000000Z","ExternalUrls":[{"Name":"IMDb","Url":"https://www.imdb.com/title/tt27033613"},{"Name":"TheTVDB","Url":"https://thetvdb.com/?tab=episode&id=9207267"},{"Name":"Trakt","Url":"https://trakt.tv/search/imdb/tt27033613"}],"Path":"/Media/番剧/W/我推的孩子/Season 1/我推的孩子 S01E01.mkv","Overview":"在妇产科医生吾郎面前出现的病患，是他神推的偶像小爱，尽管深受打击，吾郎还是决定以医生的身分支持她。但就在小爱即将临盆之际，吾郎不知被何人袭击…！？","Taglines":[],"Genres":[],"CommunityRating":9.4,"RunTimeTicks":49200420000,"Size":1761124174,"FileName":"我推的孩子 S01E01.mkv","Bitrate":2863592,"ProductionYear":2023,"IndexNumber":1,"ParentIndexNumber":1,"RemoteTrailers":[],"ProviderIds":{"Tvdb":"9207267","Imdb":"tt27033613"},"IsFolder":false,"ParentId":"904437","Type":"Episode","Studios":[],"GenreItems":[],"TagItems":[],"ParentLogoItemId":"904228","ParentBackdropItemId":"904228","ParentBackdropImageTags":["2e74331d7656872441e36403c34285cf"],"UserData":{"PlaybackPositionTicks":0,"PlayCount":1,"IsFavorite":false,"LastPlayedDate":"2024-10-16T08:44:55.0000000Z","Played":true},"SeriesName":"【我推的孩子】","SeriesId":"904228","SeasonId":"904437","PrimaryImageAspectRatio":1.7777777777777777,"SeriesPrimaryImageTag":"fb7ef6c8163205959fedc7c7303ed30b","SeasonName":"第 1 季","ImageTags":{"Primary":"070aadcfa5355ec8825f461d7d416e68"},"BackdropImageTags":[],"ParentLogoImageTag":"3350e13d94f6d1fbb2d53c83d5f2b169","MediaType":"Video","Width":1920,"Height":1080},"Server":{"Name":"Emby","Id":"8203ffe900c941298803d360b3685052","Version":"4.8.10.0"}}


有以上的格式应该就可以了

**Comment by qinu321** [comment]
谢谢大佬！我去研究一下
