### ISSUE TITLE
[功能建议]预览界面是否可以增加下载操作

### ISSUE THREAD

**Issue by paxtonyu** [wushuo894/ani-rss#57]
### 情况描述：

---

有的剧集下载下来播放不了貌似是文件损坏，但删除后 |本地存在| 一栏依旧是“是”的状态，更新订阅也无法重新下载，要是在预览界面能增加一个下载按钮或者完善相应识别逻辑就好了。辛苦大大

![image](https://github.com/user-attachments/assets/a66cd4c0-7c40-456c-b868-c292e5aa343c)

**Comment by wushuo894** [comment]
你可以把表格往右拖，有一个删除种子。删除后会再次下载

**Comment by paxtonyu** [comment]
> 你可以把表格往右拖，有一个删除种子。删除后会再次下载

哦哦好的
