### ISSUE TITLE
通知设置 集: ${episode}，会带有.0

### ISSUE THREAD

**Issue by github-xihe** [wushuo894/ani-rss#61]
程序默认开启自动跳过X.5集且文档也说明不支持 .5的重命名，所以通知这里应该把.0去掉比较符合
![image](https://github.com/user-attachments/assets/9b06a51e-c3bb-4fec-a4a4-e0d2ecf25a69)
![image](https://github.com/user-attachments/assets/17d019c8-4d89-4c3a-b932-44ae4e33cd8f)

**Comment by wushuo894** [comment]
已解决
