### ISSUE TITLE
将洗版功能独立出来（也可能我没理解对？）

### ISSUE THREAD

**Issue by wahaha216** [wushuo894/ani-rss#64]
目前我理解的是：基本设置里开启备用RSS，下载设置开启自动删除，之后在订阅里添加备用RSS。
这样设置之后备用RSS先更新的话会先下载，当下载完毕会删除任务，等主RSS的更新了会下载主RSS的，下载完成后也是会删除任务。

不知道我这样理解对不对。如果对的话，能不能不删除任务实现洗版

**Comment by wushuo894** [comment]
你的理解是对的。至于你说的删除任务实现我不是很理解

**Comment by wahaha216** [comment]
> 你的理解是对的。至于你说的删除任务实现我不是很理解

就是现在不是依赖自动删除功能吗，洗版完成后下载器应该不存在任务，我想的是保留任务

**Comment by wushuo894** [comment]
> > 你的理解是对的。至于你说的删除任务实现我不是很理解
> 
> 
> 
> 就是现在不是依赖自动删除功能吗，洗版完成后下载器应该不存在任务，我想的是保留任务

等主rss更新再删除备用rss?然后主rss不删除

**Comment by wushuo894** [comment]
你如果想保留所有任务并且不自动删除可以给重命名模版加上字幕组，关闭自动删除。这样既不会删除本地文件，也会下载主rss,并且不删除任务。你要让重命名文件不会覆盖就行了

**Comment by wahaha216** [comment]
> > > 你的理解是对的。至于你说的删除任务实现我不是很理解
> > 
> > 
> > 就是现在不是依赖自动删除功能吗，洗版完成后下载器应该不存在任务，我想的是保留任务
> 
> 等主rss更新再删除备用rss?然后主rss不删除

嗯，最终只保留主RSS的任务以及文件，重命名模板使用默认的。
因为jellyfin识别的问题，保留两个文件会导致一集出现两次。

**Comment by wushuo894** [comment]
> jellyfin

jellyfin不支持多版本视频吗？

**Comment by wushuo894** [comment]
<img width="867" alt="image" src="https://github.com/user-attachments/assets/504dc88f-1c45-4f6e-addb-d151bbabedff">

**Comment by wahaha216** [comment]
> > jellyfin
> 
> jellyfin不支持多版本视频吗？

支持，但仅限电影分类，番剧一般使用节目分类，而节目是不支持多版本的

**Comment by wushuo894** [comment]
已实现
