### ISSUE TITLE
集数识别问题

### ISSUE THREAD

**Issue by shakugannokanade** [wushuo894/ani-rss#65]
问题描述：某些字幕组的命名存在"13完"/"13END"这一类非纯数字命名，如[灰色的果实](https://mikanani.me/RSS/Bangumi?bangumiId=408&subgroupid=121)、[境界的彼方](https://mikanani.me/RSS/Bangumi?bangumiId=203&subgroupid=276)，ASS无法正常识别最后一话导致集数遗漏。已去除全部过滤关键词，关闭全局排除，应该不是过滤的问题。建议优化。

这里Mikan显示有13集，集数表示为“13完”。
![image](https://github.com/user-attachments/assets/28200cb7-cdc1-41f1-93c1-b6e3bd839808)
预览中未显示第13集，这里的13集是备用rss。
![image](https://github.com/user-attachments/assets/5822d3d4-65b9-4c68-bb24-eaa2b5353bf2)

**Comment by wushuo894** [comment]
你可以暂时使用自定义集数规则解决

或者等我更新

**Comment by wushuo894** [comment]
已更新
