### ISSUE TITLE
希望支持内封字幕

### ISSUE THREAD

**Issue by Hengmen** [wushuo894/ani-rss#67]
使用网页提供的播放器，在播放时看不到内封字幕。感觉应该不是我的设置问题，我没有找到与字幕相关的设置。

我使用的是最新版本：1.1.162
视频来源RSS：https://mikanime.tv/RSS/Bangumi?bangumiId=3495&subgroupid=615
字幕组：Kirara Fantasia

**Comment by wushuo894** [comment]
播放器组件是不支持的。
你要看的话还是用emby吧

**Comment by Hengmen** [comment]
artplayer 是只支持外挂字幕文件，我刚才看错了。
