### ISSUE TITLE
功能建议

### ISSUE THREAD

**Issue by jackdk86** [wushuo894/ani-rss#68]
![微信截图_20241030005904](https://github.com/user-attachments/assets/d6852457-2e47-4270-a84c-face554ac03e)
1:希望可以在添加番剧组时可以在简繁日这些字幕选项里点击选择就直接添加规则,这样可以在修改订阅时不用再写匹配关键字了` 
2:既然有了全局排除能不能有个全局优先呢`须然不知道这个组会不会做这个番,但字幕组接手番剧后发布番剧就可以把这些资源用来关联洗版实现全自动化
希望 越做越好解放双手

**Comment by wushuo894** [comment]
全局匹配有点鸡肋暂时不加
