### ISSUE TITLE
个别番剧无法识别本地存在

### ISSUE THREAD

**Issue by Iensuredit** [wushuo894/ani-rss#69]
大佬您好，感谢您开发了ANI-RSS！使用过程中遇到一个小问题，望您不吝赐教！

- 问题描述：
1. `[北宇治字幕组&LoliHouse]`字幕组的[`地。—关于地球的运动— (2024)`](https://mikanani.me/RSS/Bangumi?bangumiId=3488&subgroupid=370)订阅导入之后无法识别到本地存在，同期添加的其他番剧都没有遇到这个问题
2. 已确认路径无误且已开启了自动跳过及自动重命名

- 相关截图：
![11](https://github.com/user-attachments/assets/0bb7d3b1-9733-4272-a658-9d6bbe4b3fe9)
![捕获](https://github.com/user-attachments/assets/10ff6356-d689-401d-ac03-5d5cce597e11)

- 再次感谢您的付出，期待您的回复！

祝好，
天凉

**Comment by wushuo894** [comment]
字幕组命名比较鬼畜，你开一下 自定义集数规则 就行了

**Comment by Iensuredit** [comment]
> 字幕组命名比较鬼畜，你开一下 自定义集数规则 就行了

现在已经识别出来了，感谢大佬！
