### ISSUE TITLE
在网络访问正常的情况下持续提示 timed out

### ISSUE THREAD

**Issue by yonoko** [wushuo894/ani-rss#7]
问题现象：日志持续看到登陆超时和rss订阅超时，重启后也一样。截图是重启后的日志
![日志](https://github.com/user-attachments/assets/3a7371a9-1108-4f82-b27f-06152c43d269)

已在容器内通过curl 测试确认网络正常，如下图所示
![curl测试网页访问](https://github.com/user-attachments/assets/23fd61b6-2f10-4c10-ab5a-f214df4c4189)

**Comment by wushuo894** [comment]
你在ani-rss的容器里面测试过吗

**Comment by wushuo894** [comment]
> 你在ani-rss的容器里面测试过吗
> 
看着你好像就是用的容器

**Comment by wushuo894** [comment]
有没有开启代理设置

**Comment by wushuo894** [comment]
应该是你的网络太慢了，我给设置的超时时间是3秒

**Comment by yonoko** [comment]
> 你在ani-rss的容器里面测试过吗

是的，用这条命令进入容器
docker exec -i -t ani-rss /bin/bash

代理是开着的，不然也访问不了被屏蔽的蜜柑页面

**Comment by wushuo894** [comment]
> > 你在ani-rss的容器里面测试过吗
> 
> 是的，用这条命令进入容器 docker exec -i -t ani-rss /bin/bash
> 
> 代理是开着的，不然也访问不了被屏蔽的蜜柑页面

软路由的透明代理吗

**Comment by yonoko** [comment]
> 我觉得你还是贴一下你的设置吧，让我猜也太难了🤬


![图片](https://github.com/user-attachments/assets/51cd1c1c-92c2-401e-a03c-3d276c2e0b1c)
![图片](https://github.com/user-attachments/assets/36882da1-bee8-4beb-bbe8-50074e945143)
![图片](https://github.com/user-attachments/assets/1e3f78fd-f951-43a9-a62f-daa3af24e8dc)
![图片](https://github.com/user-attachments/assets/125387c8-5121-487d-b712-8c999ea83d6c)

**Comment by yonoko** [comment]
> > > 你在ani-rss的容器里面测试过吗
> > 
> > 
> > 是的，用这条命令进入容器 docker exec -i -t ani-rss /bin/bash
> > 代理是开着的，不然也访问不了被屏蔽的蜜柑页面
> 
> 软路由的透明代理吗

参考这种方式配置的 http 代理
https://docs.docker.com/engine/cli/proxy/#configure-the-docker-client

**Comment by yonoko** [comment]
> 我觉得你还是贴一下你的设置吧，让我猜也太难了🤬

![图片](https://github.com/user-attachments/assets/ca6b8da0-bc51-4811-8fae-66e11925f3fb)
![图片](https://github.com/user-attachments/assets/2730a185-d287-4727-a019-769d56a5f622)
![图片](https://github.com/user-attachments/assets/9e0711e2-be1a-4f57-ab75-2de65a62f8ce)
![图片](https://github.com/user-attachments/assets/082969fa-8be4-4731-be2f-57ceaded48f0)

**Comment by wushuo894** [comment]
> > > > 你在ani-rss的容器里面测试过吗
> > > 
> > > 
> > > 是的，用这条命令进入容器 docker exec -i -t ani-rss /bin/bash
> > > 代理是开着的，不然也访问不了被屏蔽的蜜柑页面
> > 
> > 
> > 软路由的透明代理吗
> 
> 参考这种方式配置的 http 代理 https://docs.docker.com/engine/cli/proxy/#configure-the-docker-client

你这么做感觉不对啊，如何进行分流。访问内网的qb也走代理？在ani-rss设置的就不会有这种问题，我在代码里面处理过了

**Comment by yonoko** [comment]
> > > > > 你在ani-rss的容器里面测试过吗
> > > > 
> > > > 
> > > > 是的，用这条命令进入容器 docker exec -i -t ani-rss /bin/bash
> > > > 代理是开着的，不然也访问不了被屏蔽的蜜柑页面
> > > 
> > > 
> > > 软路由的透明代理吗
> > 
> > 
> > 参考这种方式配置的 http 代理 https://docs.docker.com/engine/cli/proxy/#configure-the-docker-client
> 
> 你这么做感觉不对啊，如何进行分流。访问内网的qb也走代理？在ani-rss设置的就不会有这种问题，我在代码里面处理过了

可以看我问题说明里的 curl 测试结果，访问 qb 网页是正常的

**Comment by wushuo894** [comment]
> > > > > > 你在ani-rss的容器里面测试过吗
> > > > > 
> > > > > 
> > > > > 是的，用这条命令进入容器 docker exec -i -t ani-rss /bin/bash
> > > > > 代理是开着的，不然也访问不了被屏蔽的蜜柑页面
> > > > 
> > > > 
> > > > 软路由的透明代理吗
> > > 
> > > 
> > > 参考这种方式配置的 http 代理 https://docs.docker.com/engine/cli/proxy/#configure-the-docker-client
> > 
> > 
> > 你这么做感觉不对啊，如何进行分流。访问内网的qb也走代理？在ani-rss设置的就不会有这种问题，我在代码里面处理过了
> 
> 可以看我问题说明里的 curl 测试结果，访问 qb 网页是正常的

不设置docker的代理用.tv会有问题吗?

**Comment by yonoko** [comment]
> 应该是你的网络太慢了，我给设置的超时时间是3秒
这是我在容器里用 time curl https://mikanani.me 的测试结果，时间不到1秒，谈不上多慢吧
![图片](https://github.com/user-attachments/assets/00f5c9e7-4524-40e1-81ba-8ce7c3037f8b)

**Comment by wushuo894** [comment]
> > 应该是你的网络太慢了，我给设置的超时时间是3秒
> > 这是我在容器里用 time curl https://mikanani.me 的测试结果，时间不到1秒，谈不上多慢吧
> > ![图片](https://private-user-images.githubusercontent.com/49810645/365357143-00f5c9e7-4524-40e1-81ba-8ce7c3037f8b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU3MDE3MDgsIm5iZiI6MTcyNTcwMTQwOCwicGF0aCI6Ii80OTgxMDY0NS8zNjUzNTcxNDMtMDBmNWM5ZTctNDUyNC00MGUxLTgxYmEtOGNlN2MzMDM3ZjhiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA3VDA5MzAwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMzNDVhZTBkZTljZGIxZTQzMjAzYTI4YzBkMDUwNTJkZWNhOWUzZjkzMjE4ZWE3ZTkyODA5MTU5MzhiZDI1NDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8sJdD2FHzQzz_XZyKb7ZMUqODltddL7zMIqvcW8zDtU)

你在ani-rss的设置里再设置一下代理，如果我没记错的话java不会使用环境变量 HTTP_PROXY 设置代理的

**Comment by yonoko** [comment]
> > > > > > > 你在ani-rss的容器里面测试过吗
> > > > > > 
> > > > > > 
> > > > > > 是的，用这条命令进入容器 docker exec -i -t ani-rss /bin/bash
> > > > > > 代理是开着的，不然也访问不了被屏蔽的蜜柑页面
> > > > > 
> > > > > 
> > > > > 软路由的透明代理吗
> > > > 
> > > > 
> > > > 参考这种方式配置的 http 代理 https://docs.docker.com/engine/cli/proxy/#configure-the-docker-client
> > > 
> > > 
> > > 你这么做感觉不对啊，如何进行分流。访问内网的qb也走代理？在ani-rss设置的就不会有这种问题，我在代码里面处理过了
> > 
> > 
> > 可以看我问题说明里的 curl 测试结果，访问 qb 网页是正常的
> 
> 不设置docker的代理用.tv会有问题吗?

我的分流规则里没有对 .tv 走代理，可以用 curl 正常访问，也可以正常添加订阅，但就是不会下载。比较奇怪，上午虽然会让qB卡，但至少能下载。现在就完全没动静了。

**Comment by wushuo894** [comment]
> > > > > > > > 你在ani-rss的容器里面测试过吗
> > > > > > > 
> > > > > > > 
> > > > > > > 是的，用这条命令进入容器 docker exec -i -t ani-rss /bin/bash
> > > > > > > 代理是开着的，不然也访问不了被屏蔽的蜜柑页面
> > > > > > 
> > > > > > 
> > > > > > 软路由的透明代理吗
> > > > > 
> > > > > 
> > > > > 参考这种方式配置的 http 代理 https://docs.docker.com/engine/cli/proxy/#configure-the-docker-client
> > > > 
> > > > 
> > > > 你这么做感觉不对啊，如何进行分流。访问内网的qb也走代理？在ani-rss设置的就不会有这种问题，我在代码里面处理过了
> > > 
> > > 
> > > 可以看我问题说明里的 curl 测试结果，访问 qb 网页是正常的
> > 
> > 
> > 不设置docker的代理用.tv会有问题吗?
> 
> 我的分流规则里没有对 .tv 走代理，可以用 curl 正常访问，也可以正常添加订阅，但就是不会下载。比较奇怪，上午虽然会让qB卡，但至少能下载。现在就完全没动静了。

要不你重新创建容器？没见过这个奇怪的。按理说mikan访问不了,qb不会有问题啊

**Comment by yonoko** [comment]
> > > 应该是你的网络太慢了，我给设置的超时时间是3秒
> > > 这是我在容器里用 time curl https://mikanani.me 的测试结果，时间不到1秒，谈不上多慢吧
> > > ![图片](https://private-user-images.githubusercontent.com/49810645/365357143-00f5c9e7-4524-40e1-81ba-8ce7c3037f8b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU3MDE3MDgsIm5iZiI6MTcyNTcwMTQwOCwicGF0aCI6Ii80OTgxMDY0NS8zNjUzNTcxNDMtMDBmNWM5ZTctNDUyNC00MGUxLTgxYmEtOGNlN2MzMDM3ZjhiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA3VDA5MzAwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMzNDVhZTBkZTljZGIxZTQzMjAzYTI4YzBkMDUwNTJkZWNhOWUzZjkzMjE4ZWE3ZTkyODA5MTU5MzhiZDI1NDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8sJdD2FHzQzz_XZyKb7ZMUqODltddL7zMIqvcW8zDtU)
> 
> 你在ani-rss的设置里再设置一下代理，如果我没记错的话java不会使用环境变量 HTTP_PROXY 设置代理的
那设置格式是怎样的，是单纯的 IP 加端口还是需要加 http:// 这样的前缀？

**Comment by wushuo894** [comment]
> > > > 应该是你的网络太慢了，我给设置的超时时间是3秒
> > > > 这是我在容器里用 time curl https://mikanani.me 的测试结果，时间不到1秒，谈不上多慢吧
> > > > ![图片](https://private-user-images.githubusercontent.com/49810645/365357143-00f5c9e7-4524-40e1-81ba-8ce7c3037f8b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU3MDE3MDgsIm5iZiI6MTcyNTcwMTQwOCwicGF0aCI6Ii80OTgxMDY0NS8zNjUzNTcxNDMtMDBmNWM5ZTctNDUyNC00MGUxLTgxYmEtOGNlN2MzMDM3ZjhiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA3VDA5MzAwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMzNDVhZTBkZTljZGIxZTQzMjAzYTI4YzBkMDUwNTJkZWNhOWUzZjkzMjE4ZWE3ZTkyODA5MTU5MzhiZDI1NDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8sJdD2FHzQzz_XZyKb7ZMUqODltddL7zMIqvcW8zDtU)
> > 
> > 
> > 你在ani-rss的设置里再设置一下代理，如果我没记错的话java不会使用环境变量 HTTP_PROXY 设置代理的
> > 那设置格式是怎样的，是单纯的 IP 加端口还是需要加 http:// 这样的前缀？
我刚刚测试了一下，不用加http://
