### ISSUE TITLE
[功能建议]增加外部播放器选项

### ISSUE THREAD

**Issue by LiangPiP** [wushuo894/ani-rss#70]
我在 windows 使用 ANI-RSS 来下当季的番，但是下好的番剧只能用浏览器内部的播放器打开，我如果想用外部播放器就需要打开番剧的下载目录去找。希望能够在设置选项里面添加“设置外部播放器地址”的项目，并且如果设置了外部播放器地址后，默认在 Web 内点开番剧会用外部的播放器播放。

**Comment by wushuo894** [comment]
你安装个emby吧

**Comment by LiangPiP** [comment]
好的吧😂
