### ISSUE TITLE
网页端播放完成后没有自动点格子

### ISSUE THREAD

**Issue by Patrick-Ze** [wushuo894/ani-rss#72]
如题，我使用ani-rss的网页端，完成番剧的完整播放（等它播放到最后一秒结束自动停止），但是Bangumi那边没有自动更新格子进度。播放前已经设置好了Bangumi的token，请问是还有什么需要设置或者使用姿势不对么？

**Comment by wushuo894** [comment]
网页只是给你简单预览用的，点格子请配合emby

**Comment by Patrick-Ze** [comment]
感谢大佬超快回复。顺便好像遇到了github的bug……评论发生在未来时间……
![image](https://github.com/user-attachments/assets/e0e6f2c5-df28-477c-a718-890c4f860d39)

**Comment by wushuo894** [comment]
> 感谢大佬超快回复。顺便好像遇到了github的bug……评论发生在未来时间…… ![image](https://private-user-images.githubusercontent.com/19711799/382556767-e0e6f2c5-df28-477c-a718-890c4f860d39.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA2MjIzMDAsIm5iZiI6MTczMDYyMjAwMCwicGF0aCI6Ii8xOTcxMTc5OS8zODI1NTY3NjctZTBlNmYyYzUtZGYyOC00NzdjLWE3MTgtODkwYzRmODYwZDM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTAzVDA4MjAwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM1ZjI2ZjEyNjI2NTJlOGUzNTQ2NjcwNGRmOGU5ODFkNjdkYTU0MjRlMmRlOGY5ZmQ4YTIwODE0OGNkODJkZTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.AzamoqG4SdRWfujYy-J6TYpEouKxIEU8klNnLxPehiU)

应该采用的亚洲时区，偏差不大
