### ISSUE TITLE
在订阅番剧时,番剧的原始标题中的'-'会被替换为'―'

### ISSUE THREAD

**Issue by finalpi** [wushuo894/ani-rss#76]
如题,我在订阅本季新番`地。-关于地球的运动-`时,原始标题的符号`-`被替换为全角的中文符号`―`,变为了`地。 ―关于地球的运动―`,希望在解析rss后能保持原标题内容不变

**Comment by NtskwK** [comment]
这个标题是根据挂削数据自动修改的，建议向元数据提供网站反馈~~或手动重命名~~。
