### ISSUE TITLE
番劇改語系

### ISSUE THREAD

**Issue by lekoOwO** [wushuo894/ani-rss#77]
請問是否能讓 AniRSS 支援番劇自動改名的功能？

目前在 AB 或是 AniRSS 上，當新作品被發現後，我需要手動將劇名改為台灣的在地化翻譯，並進入下載資料夾將舊的簡中翻譯自動建立的資料夾刪除，這個過程非常繁瑣。

希望這個痛點問題能被解決，謝謝您的熱心貢獻！

**Comment by wushuo894** [comment]
已支持
