### ISSUE TITLE
[Feature] 希望添加 qBittorrent 种子分类功能

### ISSUE THREAD

**Issue by Kyakui** [wushuo894/ani-rss#79]
qb 中不只有 ANI-RSS 管理的种子，希望 ANI-RSS 在向 qb 添加种子时，可以将种子添加到一个分类，方便用户在 qb 中筛选种子

![image_1](https://github.com/user-attachments/assets/d6fd9bd8-ecbc-4144-ba25-f1f98c750448)

**Comment by wushuo894** [comment]
已更新
