### ISSUE TITLE
[Feature] 希望丰富通知内容

### ISSUE THREAD

**Issue by Kyakui** [wushuo894/ani-rss#80]
版本号：v1.1.179
我在使用 TG 通知时发现通知的文字内容只有重命名后的种子标题，如下：

![image_2](https://github.com/user-attachments/assets/e079c1be-c48f-42db-b2c2-ddfe142cb8a6)

希望能够优化排版，并添加能显示的信息，比如：
- 番剧名称：听说你们要结婚！？
- 字幕组：Lolihouse
- 季度：第 1 季
- 集数：第 2 集

**Comment by wushuo894** [comment]
已经有通知模版，你自己自定义
