### ISSUE TITLE
動畫改名後，已下載的檔案和下載中的檔案並不會自動重新命名

### ISSUE THREAD

**Issue by lekoOwO** [wushuo894/ani-rss#82]
如標題，
動畫改名後，已下載的檔案和下載中的檔案並不會自動重新命名，
資料夾也不會重新命名 (基本上就是什麼都沒做)

**Comment by wushuo894** [comment]
ani-rss只负责订阅和下载
并不负责管理番剧的功能

**Comment by lekoOwO** [comment]
ummm
ab 有這功能的關係我下意識覺得 ani-rss 也有
建議在文檔中註明

**Comment by wushuo894** [comment]
我还是给实现了，暂时支持移动，是重命名还要再等等
