### ISSUE TITLE
删除订阅时联动删除下载任务、本地目录，并触发通知/hook

### ISSUE THREAD

**Issue by akiakise** [wushuo894/ani-rss#84]
### 请勾选您确认过的前置条件

- [X] 我已经确认此功能还未实现

### 需求描述

当一季度的番剧完结后，一般会做清理动作，主要分为以下几部分：
1. 清理 ani-rss 中的订阅
2. 清理 bt 软件中的种子和已下载的文件
3. 清理媒体库（例如 Jellyfin 中下载的文件）

目前 ani-rss 的删除订阅仅实现了第一步，即只有订阅任务的清理，对于 bt 软件中的种子和文件虽然有清理代码，但是似乎无效/有bug（我测试了《漩涡》和《重来吧、魔王大人！R》，全新下载，下载完成后删除 ani-rss 中的订阅，删除完成后本地文件依然存在，且日志无异常）。

需求：希望 ani-rss 在删除订阅时可以联动删除 bt 任务、已下载文件（直接清理整个目录）、触发 webhook（低优先级，我本人使用 webhook 在下载完成后显式触发 jellyfin 媒体库的刷新）

### 实现思路

在删除订阅的接口内部完成这些动作

**Comment by wushuo894** [comment]
现有代码是删除ani-rss自己所缓存的种子

**Comment by akiakise** [comment]
是的，所以希望能增加这样的联动删除能力

**Comment by wushuo894** [comment]
已经实现

**Comment by akiakise** [comment]
太高效了
![IMG_7230](https://github.com/user-attachments/assets/80482e39-a0d8-403b-abde-3c7124257105)
