### ISSUE TITLE
定义资源优先级并保留高优先级的资源

### ISSUE THREAD

**Issue by Rirmach** [wushuo894/ani-rss#85]
### 请勾选您确认过的前置条件

- [X] 我已经确认此功能还未实现

### 需求描述

同一部作品同一集资源质量不一，有的没有中文字幕，有的清晰度不高，有的字幕是半机翻，但高质量的资源很多发布较晚。
能否以作品和剧集标记多个备选单集下载资源、定义多维度的资源优先级，每次下载时选择优先级最高的资源保证第一时间追番，后续逐步替换为更高优先级的资源

**Comment by wushuo894** [comment]
已经有洗版功能了
备用rss
