### ISSUE TITLE
本地是否存在功能不会更新状态

### ISSUE THREAD

**Issue by wjfu99** [wushuo894/ani-rss#89]
### 请勾选您确认过的前置条件

- [X] 我已经阅读了 [常见问题](https://docs.wushuo.top/faq.html) [使用文档](https://docs.wushuo.top/add-rss.html)

- [X] 我确定没有重复的issue或discussions

- [X] 我确定这是程序本身的问题而不是其他 (比如网络相关的报错)

- [X] 我确定这个问题在最新版本中没有被修复

### 运行环境

- [X] Docker

- [ ] Linux

- [ ] macOS

- [ ] Windows

- [ ] 群晖套件

### 程序版本

 v1.1.191

### 问题描述

首先感谢开发者大大，anirss太好用了，忍autobangumi很久了（各种闪退、坏种），纯纯上位替代。

番剧订阅的预览页面，“本地存在条目”无法正常更新，在删除后，“本地存在”仍显示“是”
已开启自动重命名，自动跳过功能，
<img width="754" alt="image" src="https://github.com/user-attachments/assets/47deeda2-d16b-40db-9b79-454bb916528c">
<img width="760" alt="image" src="https://github.com/user-attachments/assets/17693637-75e1-4ed9-a5e1-dd6422bf8055">

并且qBittorrent和anirss的目录挂载同步
![image](https://github.com/user-attachments/assets/421ebef9-a550-48b1-a185-e5d2e198d698)
![image](https://github.com/user-attachments/assets/17952fce-1526-4cb0-9515-ea15e0e4323c)

然而“本地存在条目”在本地文件被移除后仍然无法正常更新，例如删除了番剧“听说你们要结婚S01E07”后，“本地存在条目”仍显示“是”

<img width="984" alt="image" src="https://github.com/user-attachments/assets/38a6c13b-eeaa-4e12-9bb1-567844ca6505">
但播放界面还是能看到S01E07已经没有了
<img width="818" alt="image" src="https://github.com/user-attachments/assets/2db1f504-005b-4807-a18a-340f94461389">
期望的表现是，当本地文件移除后，预览界面中可以及时检测出文件不在了

另外还有个小问题，播放界面打开播放视频，总是会加载不出来，显示reconnect（虽然我基本也不会用这个窗口看视频）
<img width="778" alt="image" src="https://github.com/user-attachments/assets/c18a87c3-f57b-40c8-9c71-c8315e8ac323">
然后在刷新浏览器还会出现短暂的badgateway，
<img width="401" alt="image" src="https://github.com/user-attachments/assets/0ff9ea4e-d6c2-4ba6-b020-8bf00904764a">
看了下network，不知道是不是我Nginx配置的问题。
<img width="907" alt="image" src="https://github.com/user-attachments/assets/06c1bc60-dca7-47e4-8d45-c901f4c6f5c0">

期待您的回复，感谢🙏

**Comment by wushuo894** [comment]
[删除了视频-在预览中还是显示本地存在](https://docs.wushuo.top/faq.html#删除了视频-在预览中还是显示本地存在)

至于加载不出来，应该是浏览器不支持解码

**Comment by wjfu99** [comment]
感谢回复，删除种子之后确实能发现文件不在了。
但是我还是有点困惑，有几个问题希望请教：

1. 为什么本地存在要去检测种子还在不在？是避免用户主动删除文件后anirss自动自己下回来吗？
2. 有地方能一键删除种子吗？看预览界面没有多选删除种子的按钮，试了下删除缓存好像也不管用，下载设置界面有个 “自动删除”按钮不知道管不管用

再次感谢🙏

**Comment by wushuo894** [comment]
> 感谢回复，删除种子之后确实能发现文件不在了。 但是我还是有点困惑，有几个问题希望请教：
> 
> 1. 为什么本地存在要去检测种子还在不在？是避免用户主动删除文件后anirss自动自己下回来吗？
> 2. 有地方能一键删除种子吗？看预览界面没有多选删除种子的按钮，试了下删除缓存好像也不管用，下载设置界面有个 “自动删除”按钮不知道管不管用
> 
> 再次感谢🙏

1. 用于校验字幕组是否更新V2版本或者出现更新、2是对比洗版时hash是否发生变化
2. 你如果要批量删除可以在 /config/torrents 处理

**Comment by wjfu99** [comment]
好滴好滴，非常感谢~
