### ISSUE TITLE
请问 Rclone 挂载目录作为视频存储目录时如何移动临时目录中的文件到最终目录

### ISSUE THREAD

**Issue by cutiechi** [wushuo894/ani-rss#94]
### 请勾选您确认过的前置条件

- [X] 我已经阅读了 [常见问题](https://docs.wushuo.top/faq.html) [使用文档](https://docs.wushuo.top/add-rss.html)

- [X] 我确定没有重复的issue或discussions

- [ ] 我确定这是程序本身的问题而不是其他 (比如网络相关的报错)

- [ ] 我确定这个问题在最新版本中没有被修复

### 运行环境

- [X] Docker

- [ ] Linux

- [ ] macOS

- [ ] Windows

- [ ] 群晖套件

### 程序版本

v1.1.198

### 问题描述

我把 onedrive 挂载到了本地目录 /onedrive，我再 ani-rss 中配置了：
<img width="655" alt="image" src="https://github.com/user-attachments/assets/ff672e16-869e-4c53-83af-8cffbb427bdf">
按我的理解，下载的时候会到 qb 的临时目录，下载完了，会自动移动到最终目录，但是实际情况下并没有这样做，是我的配置不对吗？

**Comment by cutiechi** [comment]
> 你在qb设置过临时下载位置了吗

设置过了，是我姿势不对嘛：

<img width="1021" alt="image" src="https://github.com/user-attachments/assets/1bbdda05-4f4e-4037-b4b7-25a402d02710">

**Comment by wushuo894** [comment]
你也可以使用alist功能，会在你下载完成后自动上传

**Comment by cutiechi** [comment]
> > > 你在qb设置过临时下载位置了吗
> > 
> > 
> > 设置过了，是我姿势不对嘛：
> > <img alt="image" width="1021" src="https://private-user-images.githubusercontent.com/27606234/388383525-1bbdda05-4f4e-4037-b4b7-25a402d02710.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIxNzEwNzYsIm5iZiI6MTczMjE3MDc3NiwicGF0aCI6Ii8yNzYwNjIzNC8zODgzODM1MjUtMWJiZGRhMDUtNGY0ZS00MDM3LWI0YjctMjVhNDAyZDAyNzEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIxVDA2MzI1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE1MGZmNDMyNWVhODUyMDlmZmU3MGQxM2U5YTA2ZTVhODFlMDkxNTlmNzU4NGZmNzQ0N2EwN2Y2OWJmMmYzNjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.WhSKJMW57k7r3CMeTs-HT-qb2PEr8FJNUvcHAK-VxUo">
> 
> 我刚测试了一下是没问题的，你看看qb日志找找线索吧

好的

**Comment by cutiechi** [comment]
> 你也可以使用alist功能，会在你下载完成后自动上传

感谢大佬，我试下
