### ISSUE TITLE
重命名模板里的${episode}集模板不生效。

### ISSUE THREAD

**Issue by abo2029** [wushuo894/ani-rss#97]
### 请勾选您确认过的前置条件

- [X] 我已经阅读了 [常见问题](https://docs.wushuo.top/faq.html) [使用文档](https://docs.wushuo.top/add-rss.html)

- [X] 我确定没有重复的issue或discussions

- [X] 我确定这是程序本身的问题而不是其他 (比如网络相关的报错)

- [X] 我确定这个问题在最新版本中没有被修复

### 运行环境

- [ ] Docker

- [ ] Linux

- [ ] macOS

- [ ] Windows

- [X] 群晖套件

### 程序版本

 v1.1.201

### 问题描述

${episode}集模板  识别成  ${episodeFormat}集模板 
强迫症，之前都是按照下面图片的重命名方式，突然改的话太麻烦，麻烦大大修复下。

### 日志

![image](https://github.com/user-attachments/assets/c2339bcb-f3e4-453c-b797-8c832aee2b54)
![image](https://github.com/user-attachments/assets/356cc5db-4d64-445d-9cb4-73def5ac5ac4)

**Comment by wushuo894** [comment]
已解决
